
"use client";

import {
  LayoutDashboard,
  TrendingUp,
  ShoppingCart,
  PackageCheck,
  BarChart3,
  Truck,
  UserPlus,
  Wallet,
  UserCircle,
  Users,
  Scale,
  Calculator,
  Landmark,
  Users2,
  Database,
  CalendarCheck,
  Package as PackageIcon,
  Boxes,
  Building2,
  Sparkles,
  Rocket,
  Mail,
  LineChart,
  Briefcase,
  ClipboardCheck,
} from 'lucide-react';

export const allMenuItems = [
  { id: "main-dashboard", name: "Dashboard", icon: LayoutDashboard, href: "/sales/dashboard-overview" },
  { id: "sub-suppliers-1", name: "Supplier Entry", icon: UserPlus, href: "/sales/supplier-entry" },
  { id: "sub-suppliers-2", name: "Supplier Payments", icon: Wallet, href: "/sales/supplier-payments" },
  { id: "sub-suppliers-3", name: "Supplier Profile", icon: UserCircle, href: "/sales/supplier-profile" },
  { id: "sub-customers-1", name: "Customer Entry", icon: UserPlus, href: "/sales/customer-entry" },
  { id: "sub-customers-2", name: "Customer Payments", icon: Wallet, href: "/sales/customer-payments" },
  { id: "sub-customers-3", name: "Customer Profile", icon: UserCircle, href: "/sales/customer-profile" },
  { id: "sub-income-expense-1", name: "Income & Expense", icon: Calculator, href: "/expense-tracker" },
  { id: "sub-cash-bank-1", name: "Cash & Bank", icon: Landmark, href: "/cash-bank" },
  { id: "sub-hr-1", name: "Employee Database", icon: Database, href: "/hr/employee-database" },
  { id: "sub-hr-2", name: "Payroll", icon: Calculator, href: "/hr/payroll-management" },
  { id: "sub-inventory-1", name: "Inventory", icon: Boxes, href: "/inventory/inventory-management" },
  { id: "sub-inventory-3", name: "Purchase Orders", icon: ShoppingCart, href: "/inventory/purchase-orders" },
  { id: "sub-project-1", name: "Projects", icon: Briefcase, href: "/projects/dashboard" },
];
